export enum EnvVariableName {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',

  DATABASE_URL = 'DATABASE_URL',
  REDIS_URL = 'REDIS_URL',
  DLQ_NAME = 'DLQ_NAME',

  JWT_SECRET = 'JWT_SECRET',
  TELEGRAM_BOT_TOKEN = 'TELEGRAM_BOT_TOKEN',
  MINI_APP_URL = 'MINI_APP_URL',

  REDDY_BOT_BASE_URL = 'REDDY_BOT_BASE_URL',
  REDDY_BOT_TOKEN = 'REDDY_BOT_TOKEN',

  LOG_LEVEL = 'LOG_LEVEL',

  APP_BASE_URL = 'APP_BASE_URL',

  OTEL_ENABLED = 'OTEL_ENABLED',
  OTEL_SERVICE_NAME = 'OTEL_SERVICE_NAME',
  OTEL_EXPORTER_OTLP_ENDPOINT = 'OTEL_EXPORTER_OTLP_ENDPOINT',
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = 'OTEL_EXPORTER_OTLP_TRACES_ENDPOINT',
  OTEL_LOG_LEVEL = 'OTEL_LOG_LEVEL',
}
